namespace Zorvian.Application.DTOs.Fleet;

public sealed record CreateFleetExpenseRequest(
    DateTime ExpenseDate,
    Guid CategoryId,
    Guid? SubcategoryId,
    Guid? VehicleId,
    Guid? DriverId,
    Guid? TripId,
    Guid? RouteId,
    Guid? SupplierId,
    string Description,
    decimal Amount,
    string Currency,
    decimal ExchangeRate,
    string PaymentMethod,
    string? DocumentUrl,
    bool Reimbursable,
    Guid? AccountId
);

public sealed record UpdateFleetExpenseRequest(
    DateTime? ExpenseDate,
    Guid? CategoryId,
    Guid? SubcategoryId,
    Guid? VehicleId,
    Guid? DriverId,
    Guid? TripId,
    Guid? RouteId,
    Guid? SupplierId,
    string? Description,
    decimal? Amount,
    string? Currency,
    decimal? ExchangeRate,
    string? PaymentMethod,
    string? DocumentUrl,
    bool? Reimbursable,
    bool? Reimbursed,
    bool? Approved,
    Guid? AccountId
);

public sealed record FleetExpenseResponse(
    Guid Id,
    DateTime ExpenseDate,
    Guid CategoryId,
    string CategoryName,
    Guid? SubcategoryId,
    string? SubcategoryName,
    Guid? VehicleId,
    string? VehiclePlate,
    string? VehicleBrandModel,
    Guid? DriverId,
    string? DriverName,
    Guid? TripId,
    string? TripNumber,
    Guid? RouteId,
    string? RouteName,
    Guid? SupplierId,
    string? SupplierName,
    string Description,
    decimal Amount,
    string Currency,
    decimal ExchangeRate,
    decimal AmountBaseCurrency,
    string PaymentMethod,
    string? DocumentUrl,
    bool Reimbursable,
    bool Reimbursed,
    bool Approved,
    Guid? AccountId,
    string? AccountName,
    DateTime CreatedAt
);
