namespace Zorvian.Application.DTOs.Fleet;

public sealed record CreateVehicleRequest(
    string Code,
    string Plate,
    Guid BrandId,
    string Model,
    int Year,
    string? Vin,
    string? EngineNumber,
    string? ChassisNumber,
    string? Color,
    Guid VehicleTypeId,
    Guid FuelTypeId,
    Guid BranchId,
    decimal CurrentKm,
    decimal LoadCapacityKg,
    decimal? LoadCapacityM3,
    int? PassengerCapacity,
    string? GpsDeviceId,
    decimal? PurchaseValue,
    DateTime? PurchaseDate,
    string? ImageUrl
);

public sealed record UpdateVehicleRequest(
    string? Code,
    string? Plate,
    Guid? BrandId,
    string? Model,
    int? Year,
    string? Vin,
    string? EngineNumber,
    string? ChassisNumber,
    string? Color,
    Guid? VehicleTypeId,
    Guid? FuelTypeId,
    Guid? BranchId,
    decimal? CurrentKm,
    decimal? LoadCapacityKg,
    decimal? LoadCapacityM3,
    int? PassengerCapacity,
    string? Status,
    Guid? DriverId,
    string? GpsDeviceId,
    decimal? PurchaseValue,
    DateTime? PurchaseDate,
    string? ImageUrl
);

public sealed record VehicleResponse(
    Guid Id,
    string Code,
    string Plate,
    Guid BrandId,
    string BrandName,
    string Model,
    int Year,
    string? Vin,
    string? EngineNumber,
    string? ChassisNumber,
    string? Color,
    Guid VehicleTypeId,
    string VehicleTypeName,
    Guid FuelTypeId,
    string FuelTypeName,
    Guid BranchId,
    string BranchName,
    decimal CurrentKm,
    decimal LoadCapacityKg,
    decimal? LoadCapacityM3,
    int? PassengerCapacity,
    string Status,
    Guid? DriverId,
    string? DriverName,
    string? GpsDeviceId,
    decimal? PurchaseValue,
    DateTime? PurchaseDate,
    string? ImageUrl,
    DateTime CreatedAt
);
